#!/bin/bash

# Installer l'extension hide_code
jupyter nbextension install --py hide_code --user

# Activer l'extension hide_code pour les notebooks
jupyter nbextension enable --py hide_code

# Activer l'extension hide_code au niveau du serveur Jupyter
jupyter serverextension enable --py hide_code